__merge__: /src/api/comp_control_method.yaml
name: "majority_vote"
label: Majority Vote
summary: "A control-type method that predicts all cells to belong to the most abundant cell type in the dataset"
description: "A control-type method that predicts all cells to belong to the most abundant cell type in the dataset"
info:
  v1:
    path: openproblems/tasks/label_projection/methods/baseline.py
    commit: b3456fd73c04c28516f6df34c57e6e3e8b0dab32
  variants:
    majority_vote:
  preferred_normalization: counts
resources:
  - type: python_script
    path: script.py
engines:
  - type: docker
    image: openproblems/base_python:1
runners:
  - type: executable
  - type: nextflow
    directives: 
      label: [midtime, lowmem, lowcpu]
