__merge__: /src/api/comp_process_dataset.yaml
name: process_dataset
namespace: data_processors
arguments:
  - name: "--method"
    type: "string"
    description: "The process method to assign train/test."
    choices: ["batch", "random"]
    default: "batch"
  - name: "--obs_label"
    type: "string"
    description: "Which .obs slot to use as label."
    default: "cell_type"
  - name: "--obs_batch"
    type: "string"
    description: "Which .obs slot to use as batch covariate."
    default: "batch"
  - name: "--seed"
    type: "integer"
    description: "A seed for the subsampling."
    example: 123
resources:
  - type: python_script
    path: script.py
  - path: /common/helper_functions/subset_h5ad_by_format.py
test_resources:
  - path: /resources_test/common/pancreas
    dest: resources_test/common/pancreas
  - type: python_script
    path: /common/component_tests/run_and_check_output.py
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [highmem, midcpu, midtime]
