__merge__: ../../api/comp_method.yaml

name: geneformer
label: Geneformer
summary: Geneformer is a foundational transformer model pretrained on a large-scale corpus of single cell transcriptomes to enable context-aware predictions in settings with limited data in network biology.
description: |
  Geneformer is a context-aware, attention-based deep learning model pretrained on a large-scale corpus of single-cell transcriptomes to enable context-specific predictions in settings with limited data in network biology. Here, a pre-trained Geneformer model is fine-tuned and used to predict cell type labels for an unlabelled dataset.

info:
  preferred_normalization: counts
  test_setup:
    # override the default training parameters for quicker unit testing
    run:
      model: "Geneformer-V2-104M"
      num_train_epochs: 1
      warmup_steps: 1
      max_trials: 1

references:
  doi:
    - 10.1038/s41586-023-06139-9
    - 10.1101/2024.08.16.608180

links:
  documentation: https://geneformer.readthedocs.io/en/latest/index.html
  repository: https://huggingface.co/ctheodoris/Geneformer

arguments:
  - name: --model
    type: string
    description: String representing the Geneformer model to use
    choices:
      - Geneformer-V1-10M
      - Geneformer-V2-104M
      - Geneformer-V2-316M
    default: "Geneformer-V2-316M"
  # training parameters
  - name: --num_train_epochs
    type: integer
    description: Number of epochs to train the model
  - name: --warmup_steps
    type: integer
    description: Number of warmup steps for the learning rate scheduler
  - name: --max_trials
    type: integer
    description: Number of trials to run

resources:
  - type: python_script
    path: script.py
  - path: /src/utils/exit_codes.py

engines:
  - type: docker
    image: openproblems/base_pytorch_nvidia:1
    setup:
      - type: python
        pip:
          - pyarrow<15.0.0a0,>=14.0.1
          - huggingface_hub
          - git+https://huggingface.co/ctheodoris/Geneformer.git

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [hightime, highmem, midcpu, midgpu, midsharedmem]
