__merge__: /src/api/comp_control_method.yaml
name: "true_labels"
label: True labels
summary: "a positive control, solution labels are copied 1 to 1 to the predicted data."
description: "A positive control, where the solution labels are copied 1 to 1 to the predicted data."
info:
  v1:
    path: openproblems/tasks/label_projection/methods/baseline.py
    commit: b3456fd73c04c28516f6df34c57e6e3e8b0dab32
  preferred_normalization: counts
  variants:
    true_labels:
resources:
  - type: python_script
    path: script.py
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
runners:
  - type: executable
  - type: nextflow
    directives: 
      label: [midtime, lowmem, lowcpu]
