name: "logistic_regression"
namespace: "methods"
version: "build_main"
argument_groups:
- name: "Arguments"
  arguments:
  - type: "file"
    name: "--input_train"
    label: "Training data"
    summary: "The training data"
    info:
      format:
        type: "h5ad"
        layers:
        - type: "integer"
          name: "counts"
          description: "Raw counts"
          required: true
        - type: "double"
          name: "normalized"
          description: "Normalized counts"
          required: true
        obs:
        - type: "string"
          name: "label"
          description: "Ground truth cell type labels"
          required: true
        - type: "string"
          name: "batch"
          description: "Batch information"
          required: true
        var:
        - type: "boolean"
          name: "hvg"
          description: "Whether or not the feature is considered to be a 'highly variable\
            \ gene'"
          required: true
        - type: "double"
          name: "hvg_score"
          description: "A ranking of the features by hvg."
          required: true
        obsm:
        - type: "double"
          name: "X_pca"
          description: "The resulting PCA embedding."
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - type: "string"
          name: "normalization_id"
          description: "Which normalization was used"
          required: true
    example:
    - "resources_test/label_projection/pancreas/train.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--input_test"
    label: "Test data"
    summary: "The test data (without labels)"
    info:
      format:
        type: "h5ad"
        layers:
        - type: "integer"
          name: "counts"
          description: "Raw counts"
          required: true
        - type: "double"
          name: "normalized"
          description: "Normalized counts"
          required: true
        obs:
        - type: "string"
          name: "batch"
          description: "Batch information"
          required: true
        var:
        - type: "boolean"
          name: "hvg"
          description: "Whether or not the feature is considered to be a 'highly variable\
            \ gene'"
          required: true
        - type: "double"
          name: "hvg_score"
          description: "A ranking of the features by hvg."
          required: true
        obsm:
        - type: "double"
          name: "X_pca"
          description: "The resulting PCA embedding."
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - type: "string"
          name: "normalization_id"
          description: "Which normalization was used"
          required: true
    example:
    - "resources_test/label_projection/pancreas/test.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--output"
    label: "Prediction"
    summary: "The prediction file"
    info:
      format:
        type: "h5ad"
        obs:
        - type: "string"
          name: "label_pred"
          description: "Predicted labels for the test cells."
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - type: "string"
          name: "normalization_id"
          description: "Which normalization was used"
          required: true
        - type: "string"
          name: "method_id"
          description: "A unique identifier for the method"
          required: true
    example:
    - "resources_test/label_projection/pancreas/prediction.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
resources:
- type: "python_script"
  path: "script.py"
  is_executable: true
label: "Logistic Regression"
summary: "Logistic Regression with 100-dimensional PCA coordinates estimates parameters\
  \ for multivariate classification by minimizing cross entropy loss over cell type\
  \ classes."
description: "Logistic Regression estimates parameters of a logistic function for\n\
  multivariate classification tasks. Here, we use 100-dimensional whitened PCA\ncoordinates\
  \ as independent variables, and the model minimises the cross\nentropy loss over\
  \ all cell type classes.\n"
test_resources:
- type: "file"
  path: "resources_test/label_projection/pancreas"
  dest: "resources_test/label_projection/pancreas"
- type: "python_script"
  path: "check_config.py"
  is_executable: true
- type: "python_script"
  path: "run_and_check_output.py"
  is_executable: true
info:
  v1:
    path: "openproblems/tasks/label_projection/methods/logistic_regression.py"
    commit: "b3456fd73c04c28516f6df34c57e6e3e8b0dab32"
  preferred_normalization: "log_cp10k"
  variants:
    logistic_regression_scran:
      preferred_normalization: "log_scran_pooling"
  type: "method"
  type_info:
    label: "Method"
    summary: "A label projection method."
    description: "A label projection method to predict the labels of a new \"test\"\
      \ndataset based on an annotated \"training\" dataset.\n"
status: "enabled"
repositories:
- type: "github"
  name: "openproblems-v2"
  repo: "openproblems-bio/openproblems-v2"
  tag: "main_build"
license: "MIT"
references:
  bibtex:
  - "@book{hosmer2013applied,\n  title = {Applied logistic regression},\n  author\
    \ = {Hosmer Jr, D.W. and Lemeshow, S. and Sturdivant, R.X.},\n  year = {2013},\n\
    \  publisher = {John Wiley \\& Sons},\n  volume = {398}\n}\n"
links:
  repository: "https://github.com/scikit-learn/scikit-learn"
  docker_registry: "ghcr.io"
  documentation: "https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html"
runners:
- type: "executable"
  id: "executable"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "midmem"
    - "lowcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
  debug: false
  container: "docker"
engines:
- type: "docker"
  id: "docker"
  image: "openproblems/base_python:1.0.0"
  namespace_separator: "/"
  setup:
  - type: "python"
    user: false
    packages:
    - "scikit-learn"
    upgrade: true
  entrypoint: []
  cmd: null
build_info:
  config: "src/methods/logistic_regression/config.vsh.yaml"
  runner: "nextflow"
  engine: "docker"
  output: "target/nextflow/methods/logistic_regression"
  executable: "target/nextflow/methods/logistic_regression/main.nf"
  viash_version: "0.9.0-RC7"
  git_commit: "3aa0dff2c0fa4c3639a14dc4a5321d541ff89c59"
  git_remote: "https://github.com/openproblems-bio/task_label_projection"
package_config:
  name: "label_projection"
  version: "build_main"
  label: "Label projection"
  summary: "Automated cell type annotation from rich, labeled reference data"
  description: "A major challenge for integrating single cell datasets is creating\
    \ matching\ncell type annotations for each cell. One of the most common strategies\
    \ for\nannotating cell types is referred to as\n[\"cluster-then-annotate\"](https://www.nature.com/articles/s41576-018-0088-9)\n\
    whereby cells are aggregated into clusters based on feature similarity and\nthen\
    \ manually characterized based on differential gene expression or previously\n\
    identified marker genes. Recently, methods have emerged to build on this\nstrategy\
    \ and annotate cells using\n[known marker genes](https://www.nature.com/articles/s41592-019-0535-3).\n\
    However, these strategies pose a difficulty for integrating atlas-scale\ndatasets\
    \ as the particular annotations may not match.\n\nTo ensure that the cell type\
    \ labels in newly generated datasets match\nexisting reference datasets, some\
    \ methods align cells to a previously\nannotated [reference dataset](https://academic.oup.com/bioinformatics/article/35/22/4688/54802990)\n\
    and then _project_ labels from the reference to the new dataset.\n\nHere, we compare\
    \ methods for annotation based on a reference dataset.\nThe datasets consist of\
    \ two or more samples of single cell profiles that\nhave been manually annotated\
    \ with matching labels. These datasets are then\nsplit into training and test\
    \ batches, and the task of each method is to\ntrain a cell type classifer on the\
    \ training set and project those labels\nonto the test set.\n"
  info:
    image: "thumbnail.svg"
    test_resources:
    - type: "s3"
      path: "s3://openproblems-data/resources_test/common/pancreas/"
      dest: "resources_test/common/pancreas"
    - type: "s3"
      path: "s3://openproblems-data/resources_test/label_projection/"
      dest: "resources_test/label_projection"
  repositories:
  - type: "github"
    name: "openproblems-v2"
    repo: "openproblems-bio/openproblems-v2"
    tag: "main_build"
  viash_version: "0.9.0-RC7"
  source: "src"
  target: "target"
  config_mods:
  - ".runners[.type == \"nextflow\"].config.labels := { lowmem : \"memory = 20.Gb\"\
    , midmem : \"memory = 50.Gb\", highmem : \"memory = 100.Gb\", lowcpu : \"cpus\
    \ = 5\", midcpu : \"cpus = 15\", highcpu : \"cpus = 30\", lowtime : \"time = 1.h\"\
    , midtime : \"time = 4.h\", hightime : \"time = 8.h\", veryhightime : \"time =\
    \ 24.h\" }\n"
  authors:
  - name: "Nikolay Markov"
    roles:
    - "author"
    - "maintainer"
    info:
      github: "mxposed"
  - name: "Scott Gigante"
    roles:
    - "author"
    info:
      github: "scottgigante"
      orcid: "0000-0002-4544-2764"
  - name: "Robrecht Cannoodt"
    roles:
    - "author"
    info:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  keywords:
  - "single-cell"
  - "label projection"
  - "cell type annotation"
  license: "MIT"
  organization: "openproblems-bio"
  links:
    repository: "https://github.com/openproblems-bio/task_label_projection"
    docker_registry: "ghcr.io"
    issue_tracker: "https://github.com/openproblems-bio/task_label_projection/issues"
