__merge__: /src/api/comp_method.yaml
name: "seurat_transferdata"
label: Seurat TransferData
summary: "Seurat reference mapping predicts cell types for unlabelled cells using PCA distances, labelled anchors, and transfer anchors from Seurat, with SCTransform normalization."
description: |
  Seurat reference mapping is a cell type label transfer method provided by the
  Seurat package. Gene expression counts are first normalised by SCTransform
  before computing PCA. Then it finds mutual nearest neighbours, known as
  transfer anchors, between the labelled and unlabelled part of the data in PCA
  space, and computes each cell's distance to each of the anchor pairs.
  Finally, it uses the labelled anchors to predict cell types for unlabelled
  cells based on these distances.
references:
  doi:
    - 10.1016/j.cell.2021.04.048
links:
  repository: https://github.com/satijalab/seurat
  documentation: https://satijalab.org/seurat/articles/integration_mapping.html
info:
  v1:
    path: openproblems/tasks/label_projection/methods/seurat.py
    commit: b3456fd73c04c28516f6df34c57e6e3e8b0dab32
  preferred_normalization: log_cp10k
  variants:
    seurat:
resources:
  - type: r_script
    path: script.R
engines:
  - type: docker
    image: openproblems/base_r:1.0.0
    setup:
      - type: r
        cran: [ Matrix>=1.5.3, Seurat, rlang ]
runners:
  - type: executable
  - type: nextflow
    directives: 
      label: [midtime, highmem, highcpu]
