name: "f1"
namespace: "metrics"
version: "build_main"
argument_groups:
- name: "Arguments"
  arguments:
  - type: "file"
    name: "--input_solution"
    label: "Solution"
    summary: "The solution for the test data"
    info:
      format:
        type: "h5ad"
        layers:
        - type: "integer"
          name: "counts"
          description: "Raw counts"
          required: true
        - type: "double"
          name: "normalized"
          description: "Normalized counts"
          required: true
        obs:
        - type: "string"
          name: "label"
          description: "Ground truth cell type labels"
          required: true
        - type: "string"
          name: "batch"
          description: "Batch information"
          required: true
        var:
        - type: "boolean"
          name: "hvg"
          description: "Whether or not the feature is considered to be a 'highly variable\
            \ gene'"
          required: true
        - type: "double"
          name: "hvg_score"
          description: "A ranking of the features by hvg."
          required: true
        obsm:
        - type: "double"
          name: "X_pca"
          description: "The resulting PCA embedding."
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - name: "dataset_name"
          type: "string"
          description: "Nicely formatted name."
          required: true
        - type: "string"
          name: "dataset_url"
          description: "Link to the original source of the dataset."
          required: false
        - name: "dataset_reference"
          type: "string"
          description: "Bibtex reference of the paper in which the dataset was published."
          required: false
        - name: "dataset_summary"
          type: "string"
          description: "Short description of the dataset."
          required: true
        - name: "dataset_description"
          type: "string"
          description: "Long description of the dataset."
          required: true
        - name: "dataset_organism"
          type: "string"
          description: "The organism of the sample in the dataset."
          required: false
        - type: "string"
          name: "normalization_id"
          description: "Which normalization was used"
          required: true
    example:
    - "resources_test/label_projection/pancreas/solution.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--input_prediction"
    label: "Prediction"
    summary: "The prediction file"
    info:
      format:
        type: "h5ad"
        obs:
        - type: "string"
          name: "label_pred"
          description: "Predicted labels for the test cells."
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - type: "string"
          name: "normalization_id"
          description: "Which normalization was used"
          required: true
        - type: "string"
          name: "method_id"
          description: "A unique identifier for the method"
          required: true
    example:
    - "resources_test/label_projection/pancreas/prediction.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--output"
    label: "Score"
    summary: "Metric score file"
    info:
      format:
        type: "h5ad"
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - type: "string"
          name: "normalization_id"
          description: "Which normalization was used"
          required: true
        - type: "string"
          name: "method_id"
          description: "A unique identifier for the method"
          required: true
        - type: "string"
          name: "metric_ids"
          description: "One or more unique metric identifiers"
          multiple: true
          required: true
        - type: "double"
          name: "metric_values"
          description: "The metric values obtained for the given prediction. Must\
            \ be of same length as 'metric_ids'."
          multiple: true
          required: true
    example:
    - "resources_test/label_projection/pancreas/score.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
resources:
- type: "python_script"
  path: "script.py"
  is_executable: true
test_resources:
- type: "file"
  path: "resources_test/label_projection/pancreas"
  dest: "resources_test/label_projection/pancreas"
- type: "python_script"
  path: "check_config.py"
  is_executable: true
- type: "python_script"
  path: "run_and_check_output.py"
  is_executable: true
info:
  metrics:
  - name: "f1_weighted"
    label: "F1 weighted"
    summary: "Average weigthed support between each labels F1 score"
    description: "Calculates the F1 score for each label, and find their average weighted\
      \ by support (the number of true instances for each label). This alters 'macro'\
      \ to account for label imbalance; it can result in an F-score that is not between\
      \ precision and recall."
    references:
      doi: "10.48550/arxiv.2008.05756"
    min: 0
    max: 1
    maximize: true
    v1:
      path: "openproblems/tasks/label_projection/metrics/f1.py"
      commit: "b3456fd73c04c28516f6df34c57e6e3e8b0dab32"
  - name: "f1_macro"
    label: "F1 macro"
    summary: "Unweighted mean of each label F1-score"
    description: "Calculates the F1 score for each label, and find their unweighted\
      \ mean. This does not take label imbalance into account."
    references:
      doi: "10.48550/arxiv.2008.05756"
    min: 0
    max: 1
    maximize: true
    v1:
      path: "openproblems/tasks/label_projection/metrics/f1.py"
      commit: "b3456fd73c04c28516f6df34c57e6e3e8b0dab32"
  - name: "f1_micro"
    label: "F1 micro"
    summary: "Calculation of TP, FN and FP."
    description: "Calculates the F1 score globally by counting the total true positives,\
      \ false negatives and false positives."
    references:
      doi: "10.48550/arxiv.2008.05756"
    min: 0
    max: 1
    maximize: true
    v1:
      path: "openproblems/tasks/label_projection/metrics/f1.py"
      commit: "b3456fd73c04c28516f6df34c57e6e3e8b0dab32"
  type: "metric"
  type_info:
    label: "Metric"
    summary: "A label projection metric."
    description: "A metric for evaluating predicted labels.\n"
status: "enabled"
repositories:
- type: "github"
  name: "openproblems-v2"
  repo: "openproblems-bio/openproblems-v2"
  tag: "main_build"
license: "MIT"
links:
  repository: "https://github.com/openproblems-bio/task_label_projection"
  docker_registry: "ghcr.io"
runners:
- type: "executable"
  id: "executable"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "midmem"
    - "midcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
  debug: false
  container: "docker"
engines:
- type: "docker"
  id: "docker"
  image: "openproblems/base_python:1.0.0"
  namespace_separator: "/"
  setup:
  - type: "python"
    user: false
    packages:
    - "scikit-learn"
    upgrade: true
  entrypoint: []
  cmd: null
build_info:
  config: "src/metrics/f1/config.vsh.yaml"
  runner: "nextflow"
  engine: "docker"
  output: "target/nextflow/metrics/f1"
  executable: "target/nextflow/metrics/f1/main.nf"
  viash_version: "0.9.0-RC7"
  git_commit: "d2ed35e34bf48e217d8d131ded4ffbff01051d74"
  git_remote: "https://github.com/openproblems-bio/task_label_projection"
package_config:
  name: "task_label_projection"
  version: "build_main"
  label: "Label projection"
  summary: "Automated cell type annotation from rich, labeled reference data"
  description: "A major challenge for integrating single cell datasets is creating\
    \ matching\ncell type annotations for each cell. One of the most common strategies\
    \ for\nannotating cell types is referred to as\n[\"cluster-then-annotate\"](https://www.nature.com/articles/s41576-018-0088-9)\n\
    whereby cells are aggregated into clusters based on feature similarity and\nthen\
    \ manually characterized based on differential gene expression or previously\n\
    identified marker genes. Recently, methods have emerged to build on this\nstrategy\
    \ and annotate cells using\n[known marker genes](https://www.nature.com/articles/s41592-019-0535-3).\n\
    However, these strategies pose a difficulty for integrating atlas-scale\ndatasets\
    \ as the particular annotations may not match.\n\nTo ensure that the cell type\
    \ labels in newly generated datasets match\nexisting reference datasets, some\
    \ methods align cells to a previously\nannotated [reference dataset](https://academic.oup.com/bioinformatics/article/35/22/4688/54802990)\n\
    and then _project_ labels from the reference to the new dataset.\n\nHere, we compare\
    \ methods for annotation based on a reference dataset.\nThe datasets consist of\
    \ two or more samples of single cell profiles that\nhave been manually annotated\
    \ with matching labels. These datasets are then\nsplit into training and test\
    \ batches, and the task of each method is to\ntrain a cell type classifer on the\
    \ training set and project those labels\nonto the test set.\n"
  info:
    image: "thumbnail.svg"
    test_resources:
    - type: "s3"
      path: "s3://openproblems-data/resources_test/common/pancreas/"
      dest: "resources_test/common/pancreas"
    - type: "s3"
      path: "s3://openproblems-data/resources_test/label_projection/"
      dest: "resources_test/label_projection"
  repositories:
  - type: "github"
    name: "openproblems-v2"
    repo: "openproblems-bio/openproblems-v2"
    tag: "main_build"
  viash_version: "0.9.0-RC7"
  source: "src"
  target: "target"
  config_mods:
  - ".runners[.type == \"nextflow\"].config.labels := { lowmem : \"memory = 20.Gb\"\
    , midmem : \"memory = 50.Gb\", highmem : \"memory = 100.Gb\", lowcpu : \"cpus\
    \ = 5\", midcpu : \"cpus = 15\", highcpu : \"cpus = 30\", lowtime : \"time = 1.h\"\
    , midtime : \"time = 4.h\", hightime : \"time = 8.h\", veryhightime : \"time =\
    \ 24.h\" }\n"
  authors:
  - name: "Nikolay Markov"
    roles:
    - "author"
    - "maintainer"
    info:
      github: "mxposed"
  - name: "Scott Gigante"
    roles:
    - "author"
    info:
      github: "scottgigante"
      orcid: "0000-0002-4544-2764"
  - name: "Robrecht Cannoodt"
    roles:
    - "author"
    info:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  keywords:
  - "single-cell"
  - "label projection"
  - "cell type annotation"
  license: "MIT"
  organization: "openproblems-bio"
  links:
    repository: "https://github.com/openproblems-bio/task_label_projection"
    docker_registry: "ghcr.io"
    issue_tracker: "https://github.com/openproblems-bio/task_label_projection/issues"
