__merge__: /src/api/comp_control_method.yaml
name: "random_labels"
label: Random Labels
summary: "a negative control, where the labels are randomly predicted."
description: "A negative control, where the labels are randomly predicted without training the data."
info:
  v1:
    path: openproblems/tasks/label_projection/methods/baseline.py
    commit: b3456fd73c04c28516f6df34c57e6e3e8b0dab32
  preferred_normalization: counts
  variants:
    random_labels:
resources:
  - type: python_script
    path: script.py
engines:
  - type: docker
    image: openproblems/base_python:1
    setup:
      - type: python
        packages: scanpy
runners:
  - type: executable
  - type: nextflow
    directives: 
      label: [midtime, lowmem, lowcpu]
